# Generated by Django 3.0.4 on 2020-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> descriptions'),
        ),
    ]
